wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.16
    start_time: 1678441656.177229
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.8.16
      5: 0.13.10
      8:
      - 5
alpha:
  desc: null
  value: 0.5
cuda:
  desc: null
  value: true
dilation:
  desc: null
  value: 10
entropy_coef:
  desc: null
  value: 0.001
env_max_step:
  desc: null
  value: 300
env_name:
  desc: null
  value: MiniGrid-FourRooms-v0
eps:
  desc: null
  value: 0.1
gamma_m:
  desc: null
  value: 1
gamma_w:
  desc: null
  value: 1
grad_clip:
  desc: null
  value: 5.0
grid_size:
  desc: null
  value: 19
hidden_dim_manager:
  desc: null
  value: 256
hidden_dim_worker:
  desc: null
  value: 64
lr:
  desc: null
  value: 0.005
max_steps:
  desc: null
  value: 100000000
mlp:
  desc: null
  value: 1
num_steps:
  desc: null
  value: 1000
num_workers:
  desc: null
  value: 32
reward_reg:
  desc: null
  value: 1
run_name:
  desc: null
  value: baseline
seed:
  desc: null
  value: 0
time_horizon:
  desc: null
  value: 10
whole:
  desc: null
  value: 1
